language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
env:
  global:
    - VALIDATE_USER="test"
    - VALIDATE_PASS="test"
    - VALIDATE_API="http://melinda.kansalliskirjasto.fi/api/latest"
